[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
cache_path  = 'cache'

fs_permissions = [{ access = "read-write", path = "./deployments"}, { access = "read", path = "./"}]

[profile.solc]
optimizer = true
optimizer-runs = 200

